name: CI/CD
on:
    push:
        branches: ["main"] # Triggers on direct pushes to main (including PR merges)
        tags: ["v*.*.*"]  # Trigger when a tag like "v1.0.0" is pushed
    pull_request:
        branches: ["main"] # Triggers when a PR is opened/updated against main

jobs:
  # Test, and build jobs can run on both `push` and `pull_request`
    test:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Golang
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Run tests
              run: go test -v ./...

    go-build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Golang
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Build binary
              run: go build -v .
